### ISSUE TITLE
On text inputs, the cursor remains in the starting position

### ISSUE THREAD

**Issue by mijogu** [mijogu/wheresmyfav#1]

**Comment by iconico** [comment]
@mijogu Seems to work fine for me, where are you seeing this?

**Comment by mijogu** [comment]
On my phone. Pixel XL

**Comment by iconico** [comment]
@mijogu I meant which page? got a screenshot?

**Comment by iconico** [comment]
Weird, I'm going to close this, works fine on my S8.
